komodo_2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  base_rotation_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_2_base_rotation_joint
    pid: {p: 500.0, i: 0.00, d: 0}
  shoulder_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_2_shoulder_joint
    pid: {p: 500.0, i: 0, d: 0.0}
  elbow1_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_2_elbow1_joint
    pid: {p: 700.0, i: 0, d: 0.0}
  elbow2_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_2_elbow2_joint
    pid: {p: 700.0, i: 0, d: 0.0}
  wrist_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_2_wrist_joint
    pid: {p: 500.0, i: 0.0, d: 0.0}
  left_finger_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_2_left_finger_joint
    pid: {p: 500.0, i: 0.0, d: 0.0}
  right_finger_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_2_right_finger_joint
    pid: {p: 500.0, i: 0.0, d: 0.0}
